server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: edgecloud-device-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/device_db}
    username: ${SPRING_DATASOURCE_USERNAME:device_user}
    password: ${SPRING_DATASOURCE_PASSWORD:device_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always