package com.edgecloud.device.controller;
import com.edgecloud.device.dto.*;import com.edgecloud.device.security.EdgeCloudJwtAuthenticationToken;import com.edgecloud.device.service.DeviceOrganisationService;import jakarta.validation.Valid;import java.util.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/management/projects/{projectId}") public class DeviceOrganisationController {
 private final DeviceOrganisationService service;public DeviceOrganisationController(DeviceOrganisationService service){this.service=service;}private String token(EdgeCloudJwtAuthenticationToken a){return (String)a.getCredentials();}
 @GetMapping("/groups") public List<DeviceGroupResponse> groups(@PathVariable UUID projectId,@RequestParam(defaultValue="")String search,EdgeCloudJwtAuthenticationToken a){return service.groups(projectId,search,token(a));}
 @GetMapping("/groups/{id}") public DeviceGroupResponse group(@PathVariable UUID projectId,@PathVariable UUID id,EdgeCloudJwtAuthenticationToken a){return service.group(projectId,id,token(a));}
 @PostMapping("/groups") public ResponseEntity<DeviceGroupResponse> createGroup(@PathVariable UUID projectId,@Valid @RequestBody DeviceGroupRequest r,EdgeCloudJwtAuthenticationToken a){return ResponseEntity.status(HttpStatus.CREATED).body(service.createGroup(projectId,r,a.getUserId(),token(a)));}
 @PutMapping("/groups/{id}") public DeviceGroupResponse updateGroup(@PathVariable UUID projectId,@PathVariable UUID id,@Valid @RequestBody DeviceGroupRequest r,EdgeCloudJwtAuthenticationToken a){return service.updateGroup(projectId,id,r,a.getUserId(),token(a));}
 @DeleteMapping("/groups/{id}") public ResponseEntity<Void> deleteGroup(@PathVariable UUID projectId,@PathVariable UUID id,EdgeCloudJwtAuthenticationToken a){service.deleteGroup(projectId,id,token(a));return ResponseEntity.noContent().build();}
 @GetMapping("/groups/{id}/devices") public List<DeviceGroupMembershipResponse> members(@PathVariable UUID projectId,@PathVariable UUID id,EdgeCloudJwtAuthenticationToken a){return service.members(projectId,id,token(a));}
 @PostMapping("/groups/{id}/devices") public List<DeviceGroupMembershipResponse> assign(@PathVariable UUID projectId,@PathVariable UUID id,@Valid @RequestBody DeviceIdsRequest r,EdgeCloudJwtAuthenticationToken a){return service.assignDevices(projectId,id,r.deviceIds(),a.getUserId(),token(a));}
 @DeleteMapping("/groups/{id}/devices/{deviceId}") public ResponseEntity<Void> remove(@PathVariable UUID projectId,@PathVariable UUID id,@PathVariable UUID deviceId,EdgeCloudJwtAuthenticationToken a){service.removeDevice(projectId,id,deviceId,token(a));return ResponseEntity.noContent().build();}
 @GetMapping("/tags") public List<DeviceTagResponse> tags(@PathVariable UUID projectId,@RequestParam(defaultValue="")String search,EdgeCloudJwtAuthenticationToken a){return service.tags(projectId,search,token(a));}
 @PostMapping("/tags") public ResponseEntity<DeviceTagResponse> createTag(@PathVariable UUID projectId,@Valid @RequestBody DeviceTagRequest r,EdgeCloudJwtAuthenticationToken a){return ResponseEntity.status(HttpStatus.CREATED).body(service.createTag(projectId,r,a.getUserId(),token(a)));}
 @PutMapping("/tags/{id}") public DeviceTagResponse updateTag(@PathVariable UUID projectId,@PathVariable UUID id,@Valid @RequestBody DeviceTagRequest r,EdgeCloudJwtAuthenticationToken a){return service.updateTag(projectId,id,r,a.getUserId(),token(a));}
 @DeleteMapping("/tags/{id}") public ResponseEntity<Void> deleteTag(@PathVariable UUID projectId,@PathVariable UUID id,EdgeCloudJwtAuthenticationToken a){service.deleteTag(projectId,id,token(a));return ResponseEntity.noContent().build();}
 @GetMapping("/devices/{deviceId}/tags") public List<DeviceTagResponse> deviceTags(@PathVariable UUID projectId,@PathVariable UUID deviceId,EdgeCloudJwtAuthenticationToken a){return service.deviceTags(projectId,deviceId,token(a));}
 @PutMapping("/devices/{deviceId}/tags") public List<DeviceTagResponse> assignTags(@PathVariable UUID projectId,@PathVariable UUID deviceId,@Valid @RequestBody DeviceTagIdsRequest r,EdgeCloudJwtAuthenticationToken a){return service.assignTags(projectId,deviceId,r.tagIds(),a.getUserId(),token(a));}
 @DeleteMapping("/devices/{deviceId}/tags/{tagId}") public ResponseEntity<Void> removeTag(@PathVariable UUID projectId,@PathVariable UUID deviceId,@PathVariable UUID tagId,EdgeCloudJwtAuthenticationToken a){service.removeTag(projectId,deviceId,tagId,token(a));return ResponseEntity.noContent().build();}
}
