package com.edgecloud.device.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import com.edgecloud.device.dto.*; import com.edgecloud.device.entity.*; import com.edgecloud.device.exception.*; import com.edgecloud.device.repository.*; import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.test.util.ReflectionTestUtils;

class DeviceConfigurationServiceImplTest {
 @Mock EdgeDeviceRepository devices; @Mock DeviceConfigurationRepository configs; @Mock DeviceConfigurationVersionRepository versions; @Mock DeviceConfigurationTemplateRepository templates;
 DeviceConfigurationServiceImpl service; UUID id=UUID.randomUUID(),actor=UUID.randomUUID(); EdgeDevice device;
 @BeforeEach void setup(){MockitoAnnotations.openMocks(this);service=new DeviceConfigurationServiceImpl(devices,configs,versions,templates,new ObjectMapper());device=new EdgeDevice();ReflectionTestUtils.setField(device,"id",id);device.setDeviceName("alpha");device.setDeviceType("SENSOR");device.setIpAddress("10.0.0.1");device.prePersist();when(devices.findById(id)).thenReturn(Optional.of(device));when(devices.findByIdForUpdate(id)).thenReturn(Optional.of(device));when(configs.save(any())).thenAnswer(i->i.getArgument(0));when(versions.save(any())).thenAnswer(i->i.getArgument(0));}
 DeviceConfigurationRequest request(int polling){return new DeviceConfigurationRequest(polling,30,90,60,DeviceEnvironment.TESTING,"https://edge.example/api",DeviceLoggingLevel.DEBUG,List.of("edge","lab"));}
 DeviceConfiguration config(){DeviceConfiguration c=new DeviceConfiguration(id);c.setPollingIntervalSeconds(10);c.setHeartbeatIntervalSeconds(20);c.setHeartbeatTimeoutSeconds(60);c.setMetricsCollectionIntervalSeconds(30);c.setEnvironment(DeviceEnvironment.DEVELOPMENT);c.setApiEndpoint("");c.setLoggingLevel(DeviceLoggingLevel.INFO);c.setTagsJson("[]");c.setVersion(1);return c;}
 DeviceConfigurationTemplate template(UUID templateId){DeviceConfigurationTemplate t=new DeviceConfigurationTemplate(templateId);t.setName("Production");t.setPollingIntervalSeconds(120);t.setHeartbeatIntervalSeconds(60);t.setHeartbeatTimeoutSeconds(180);t.setMetricsCollectionIntervalSeconds(120);t.setEnvironment(DeviceEnvironment.PRODUCTION);t.setApiEndpoint("https://prod.example/api");t.setLoggingLevel(DeviceLoggingLevel.WARN);t.setTagsJson("[\"production\"]");return t;}
 DeviceConfigurationTemplateRequest templateRequest(){return new DeviceConfigurationTemplateRequest("Production","Safe defaults",120,60,180,120,DeviceEnvironment.PRODUCTION,"https://prod.example/api",DeviceLoggingLevel.WARN,List.of("production"));}

 @Test void returnsDefaultWithoutPersisting(){var r=service.get(id);assertEquals(0,r.version());assertEquals(DeviceEnvironment.DEVELOPMENT,r.environment());verify(configs).findById(id);verify(configs,never()).save(any());}
 @Test void updateCreatesAtomicVersion(){when(configs.findForUpdate(id)).thenReturn(Optional.empty());var r=service.update(id,request(90),actor);assertEquals(1,r.version());assertEquals(List.of("edge","lab"),r.tags());verify(configs).save(any());verify(versions).save(any());}
 @Test void unchangedConfigurationDoesNotCreateVersion(){DeviceConfiguration c=config();var r=new DeviceConfigurationRequest(10,20,60,30,DeviceEnvironment.DEVELOPMENT,"",DeviceLoggingLevel.INFO,List.of());when(configs.findForUpdate(id)).thenReturn(Optional.of(c));assertEquals(1,service.update(id,r,actor).version());verify(configs,never()).save(any());verifyNoInteractions(versions);}
 @Test void historyIsNewestFirstRepositoryOrder(){DeviceConfiguration c=config();DeviceConfigurationVersion v=new DeviceConfigurationVersion(c,"UPDATED","pollingIntervalSeconds",actor);when(versions.findByDeviceIdOrderByVersionDesc(id)).thenReturn(List.of(v));assertEquals(1,service.history(id).get(0).version());}
 @Test void restoreCreatesNewVersion(){DeviceConfiguration current=config();DeviceConfiguration old=config();old.setPollingIntervalSeconds(5);old.setVersion(1);DeviceConfigurationVersion source=new DeviceConfigurationVersion(old,"UPDATED","pollingIntervalSeconds",actor);current.setVersion(2);when(versions.findByDeviceIdAndVersion(id,1)).thenReturn(Optional.of(source));when(configs.findForUpdate(id)).thenReturn(Optional.of(current));var r=service.restore(id,1,actor);assertEquals(3,r.version());assertEquals(5,r.pollingIntervalSeconds());verify(versions).save(argThat(v->v.getAction().equals("RESTORED")));}
 @Test void createsAndValidatesUniqueTemplate(){when(templates.save(any())).thenAnswer(i->i.getArgument(0));assertEquals("Production",service.createTemplate(templateRequest(),actor).name());when(templates.existsByNameIgnoreCase("Production")).thenReturn(true);assertThrows(DuplicateConfigurationTemplateException.class,()->service.createTemplate(templateRequest(),actor));}
 @Test void appliesTemplateAndCreatesVersion(){UUID tid=UUID.randomUUID();when(templates.findById(tid)).thenReturn(Optional.of(template(tid)));when(configs.findForUpdate(id)).thenReturn(Optional.empty());var r=service.applyTemplate(id,tid,actor);assertEquals(DeviceEnvironment.PRODUCTION,r.environment());assertEquals(1,r.version());verify(versions).save(argThat(v->v.getAction().equals("TEMPLATE_APPLIED")));}
 @Test void persistenceFailurePropagatesForTransactionRollback(){when(configs.findForUpdate(id)).thenReturn(Optional.empty());when(versions.save(any())).thenThrow(new RuntimeException("database failure"));assertThrows(RuntimeException.class,()->service.update(id,request(90),actor));}
 @Test void inactiveDeviceIsReadOnlyButReadable(){device.setActive(false);assertEquals(0,service.get(id).version());assertThrows(InvalidDeviceLifecycleException.class,()->service.update(id,request(90),actor));}
 @Test void missingOrDeletedDeviceIsRejected(){when(devices.findById(id)).thenReturn(Optional.empty());when(devices.findByIdForUpdate(id)).thenReturn(Optional.empty());assertThrows(DeviceNotFoundException.class,()->service.get(id));assertThrows(DeviceNotFoundException.class,()->service.update(id,request(90),actor));}
 @Test void configurationDoesNotMutateDeviceMetadata(){String name=device.getDeviceName();when(configs.findForUpdate(id)).thenReturn(Optional.empty());service.update(id,request(90),actor);assertEquals(name,device.getDeviceName());verify(devices,never()).save(any());}
}
