package com.edgecloud.device.service;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import com.edgecloud.device.dto.*;import com.edgecloud.device.entity.*;import com.edgecloud.device.exception.*;import com.edgecloud.device.repository.*;import java.util.*;import org.junit.jupiter.api.*;import org.mockito.*;
class DeviceOrganisationServiceImplTest {
 @Mock DeviceGroupRepository groups;@Mock DeviceTagRepository tags;@Mock DeviceGroupMembershipRepository memberships;@Mock DeviceTagAssignmentRepository assignments;@Mock EdgeDeviceRepository devices;@Mock ProjectScopeClient projects;DeviceOrganisationServiceImpl service;UUID project=UUID.randomUUID(),actor=UUID.randomUUID(),gid=UUID.randomUUID(),tid=UUID.randomUUID(),did=UUID.randomUUID();DeviceGroup group;DeviceTag tag;
 @BeforeEach void setup(){MockitoAnnotations.openMocks(this);service=new DeviceOrganisationServiceImpl(groups,tags,memberships,assignments,devices,projects);group=new DeviceGroup(gid,project);group.setName("Production");group.setNormalisedName("production");tag=new DeviceTag(tid,project);tag.setName("Critical");tag.setNormalisedName("critical");when(groups.save(any())).thenAnswer(i->i.getArgument(0));when(tags.save(any())).thenAnswer(i->i.getArgument(0));when(groups.findByIdAndProjectId(gid,project)).thenReturn(Optional.of(group));when(tags.findByIdAndProjectId(tid,project)).thenReturn(Optional.of(tag));when(memberships.findByGroupIdOrderByAssignedAtAsc(gid)).thenReturn(new ArrayList<>());}
 @Test void createsNormalisedProjectGroup(){var r=service.createGroup(project,new DeviceGroupRequest("  Factory   Floor ","Devices"),actor,"t");assertEquals("Factory Floor",r.name());verify(groups).existsByProjectIdAndNormalisedName(project,"factory floor");}
 @Test void rejectsCaseAndWhitespaceDuplicateGroup(){when(groups.existsByProjectIdAndNormalisedName(project,"production")).thenReturn(true);assertThrows(OrganisationConflictException.class,()->service.createGroup(project,new DeviceGroupRequest(" PRODUCTION ",""),actor,"t"));}
 @Test void editsListsAndSearchesGroups(){when(groups.findByProjectIdAndNameContainingIgnoreCaseOrderByNameAsc(project,"prod")).thenReturn(List.of(group));assertEquals(1,service.groups(project," prod ","t").size());assertEquals("Updated",service.updateGroup(project,gid,new DeviceGroupRequest("Updated",""),actor,"t").name());}
 @Test void assignsMultipleDevicesIdempotently(){UUID second=UUID.randomUUID();when(devices.existsById(any())).thenReturn(true);when(memberships.existsById(new DeviceGroupMembership.Id(gid,did))).thenReturn(true);service.assignDevices(project,gid,List.of(did,second,second),actor,"t");verify(memberships,times(1)).save(any());verify(projects,times(2)).requireDeviceAssociation(eq(project),any(),eq("t"));}
 @Test void rejectsCrossProjectDeviceAssignment(){doThrow(new ProjectScopeAccessException("denied")).when(projects).requireDeviceAssociation(project,did,"t");assertThrows(ProjectScopeAccessException.class,()->service.assignDevices(project,gid,List.of(did),actor,"t"));verify(memberships,never()).save(any());}
 @Test void removesMembershipWithoutDeletingDevice(){service.removeDevice(project,gid,did,"t");verify(memberships).deleteByGroupIdAndDeviceId(gid,did);verify(devices,never()).deleteById(any());}
 @Test void rejectsPopulatedGroupDeletion(){when(memberships.countByGroupId(gid)).thenReturn(1L);assertThrows(OrganisationConflictException.class,()->service.deleteGroup(project,gid,"t"));verify(groups,never()).delete(any());}
 @Test void deletesEmptyGroupWithoutDeletingDevice(){service.deleteGroup(project,gid,"t");verify(groups).delete(group);verify(devices,never()).delete(any(EdgeDevice.class));}
 @Test void createsRejectsAndEditsTags(){assertEquals("Critical",service.createTag(project,new DeviceTagRequest(" Critical ",""),actor,"t").name());when(tags.existsByProjectIdAndNormalisedName(project,"critical")).thenReturn(true);assertThrows(OrganisationConflictException.class,()->service.createTag(project,new DeviceTagRequest("CRITICAL",""),actor,"t"));assertEquals("Remote",service.updateTag(project,tid,new DeviceTagRequest("Remote",""),actor,"t").name());}
 @Test void searchesTags(){when(tags.findByProjectIdAndNameContainingIgnoreCaseOrderByNameAsc(project,"crit")).thenReturn(List.of(tag));assertEquals(1,service.tags(project," crit ","t").size());}
 @Test void assignsMultipleTagsAndReplacesOldAssignments(){UUID second=UUID.randomUUID(),old=UUID.randomUUID();DeviceTag other=new DeviceTag(second,project);other.setName("Linux");when(devices.existsById(did)).thenReturn(true);when(tags.findAllByIdInAndProject(any(),eq(project))).thenReturn(List.of(tag,other));when(assignments.findByDeviceIdOrderByAssignedAtAsc(did)).thenReturn(List.of(new DeviceTagAssignment(old,did,actor)));var result=service.assignTags(project,did,List.of(tid,second),actor,"t");assertEquals(2,result.size());verify(assignments).delete(any(DeviceTagAssignment.class));verify(assignments,times(2)).save(any());}
 @Test void rejectsCrossProjectTagAssignment(){when(devices.existsById(did)).thenReturn(true);when(tags.findAllByIdInAndProject(any(),eq(project))).thenReturn(List.of());assertThrows(ProjectScopeAccessException.class,()->service.assignTags(project,did,List.of(tid),actor,"t"));}
 @Test void removesAndDeletesTagWithoutDeletingDevices(){service.removeTag(project,did,tid,"t");verify(assignments).deleteByTagIdAndDeviceId(tid,did);service.deleteTag(project,tid,"t");verify(assignments).deleteByTagId(tid);verify(tags).delete(tag);verify(devices,never()).delete(any(EdgeDevice.class));}
}
