package com.edgecloud.device.service;
import static org.mockito.Mockito.*;import static org.assertj.core.api.Assertions.*;import com.edgecloud.device.config.DeviceThresholdProperties;import com.edgecloud.device.dto.DeviceHeartbeatRequest;import com.edgecloud.device.entity.*;import com.edgecloud.device.exception.InvalidDeviceLifecycleException;import com.edgecloud.device.repository.EdgeDeviceRepository;import java.time.LocalDateTime;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.test.util.ReflectionTestUtils;
@ExtendWith(MockitoExtension.class) class DeviceRegistrationServiceImplTest {
 @Mock EdgeDeviceRepository repository;@Mock DeviceHeartbeatService heartbeat;DeviceRegistrationServiceImpl service;UUID id=UUID.randomUUID();EdgeDevice device;
 @BeforeEach void setup(){service=new DeviceRegistrationServiceImpl(repository,new DeviceThresholdProperties(60),heartbeat);device=new EdgeDevice();ReflectionTestUtils.setField(device,"id",id);device.setDeviceName("node");device.setDeviceType("EDGE");device.setIpAddress("10.0.0.1");device.prePersist();lenient().when(repository.findById(id)).thenReturn(Optional.of(device));}
 @Test void delegatesScheduledEvaluationToCentralPolicy(){service.evaluateDeviceStatuses();verify(heartbeat).evaluateAll(any(LocalDateTime.class));}
 @Test void heartbeatDelegatesAndPreservesResponse(){when(repository.findById(id)).thenReturn(Optional.of(device));service.processHeartbeat(new DeviceHeartbeatRequest(id,null));verify(heartbeat).record(id,null);assertThat(repository.findById(id)).contains(device);}
 @Test void inactiveDeviceIsRejected(){device.setActive(false);assertThatThrownBy(()->service.processHeartbeat(new DeviceHeartbeatRequest(id,null))).isInstanceOf(InvalidDeviceLifecycleException.class);verifyNoInteractions(heartbeat);}
}
