package com.edgecloud.device.controller;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import com.edgecloud.device.security.*; import com.edgecloud.device.service.DeviceConfigurationService;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.context.annotation.Import; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(DeviceConfigurationController.class) @Import({DeviceSecurityConfig.class,EdgeCloudJwtAuthenticationFilter.class,JwtService.class})
class DeviceConfigurationControllerTest {
 @Autowired MockMvc mvc; @MockBean DeviceConfigurationService service; String id="11111111-1111-1111-1111-111111111111"; String template="22222222-2222-2222-2222-222222222222";
 String body="{\"pollingIntervalSeconds\":60,\"heartbeatIntervalSeconds\":30,\"heartbeatTimeoutSeconds\":90,\"metricsCollectionIntervalSeconds\":60,\"environment\":\"TESTING\",\"apiEndpoint\":\"https://edge.example/api\",\"loggingLevel\":\"INFO\",\"tags\":[\"lab\"]}";
 String templateBody="{\"name\":\"Testing\",\"description\":\"Defaults\",\"pollingIntervalSeconds\":60,\"heartbeatIntervalSeconds\":30,\"heartbeatTimeoutSeconds\":90,\"metricsCollectionIntervalSeconds\":60,\"environment\":\"TESTING\",\"apiEndpoint\":\"https://edge.example/api\",\"loggingLevel\":\"INFO\",\"tags\":[\"lab\"]}";
 @Test void unauthenticatedIsRejected()throws Exception{mvc.perform(get("/management/"+id+"/configuration")).andExpect(status().isUnauthorized());}
 @Test void viewerCannotReadOrMutate()throws Exception{String t=bearer("VIEWER");mvc.perform(get("/management/"+id+"/configuration").header("Authorization",t)).andExpect(status().isForbidden());mvc.perform(put("/management/"+id+"/configuration").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());}
 @Test void projectScopedRoleCannotCrossAccessPlatformConfiguration()throws Exception{mvc.perform(get("/management/"+id+"/configuration").header("Authorization",bearer("PROJECT_ADMIN"))).andExpect(status().isForbidden());}
 @Test void operatorCanReadUpdateRestoreAndApply()throws Exception{String t=bearer("OPERATOR");mvc.perform(get("/management/"+id+"/configuration").header("Authorization",t)).andExpect(status().isOk());mvc.perform(put("/management/"+id+"/configuration").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());mvc.perform(post("/management/"+id+"/configuration/restore/1").header("Authorization",t)).andExpect(status().isOk());mvc.perform(post("/management/"+id+"/configuration/template/"+template).header("Authorization",t)).andExpect(status().isOk());}
 @Test void invalidIntervalsAndEndpointAreRejected()throws Exception{String bad=body.replace("\"pollingIntervalSeconds\":60","\"pollingIntervalSeconds\":0").replace("https://edge.example/api","not-a-url");mvc.perform(put("/management/"+id+"/configuration").header("Authorization",bearer("ADMIN")).contentType(MediaType.APPLICATION_JSON).content(bad)).andExpect(status().isBadRequest());}
 @Test void operatorCannotCreateOrUpdateTemplates()throws Exception{String t=bearer("OPERATOR");mvc.perform(post("/management/configuration-templates").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(templateBody)).andExpect(status().isForbidden());mvc.perform(put("/management/configuration-templates/"+template).header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(templateBody)).andExpect(status().isForbidden());}
 @Test void adminCanManageTemplates()throws Exception{String t=bearer("ADMIN");mvc.perform(post("/management/configuration-templates").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(templateBody)).andExpect(status().isCreated());mvc.perform(put("/management/configuration-templates/"+template).header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(templateBody)).andExpect(status().isOk());}
 private String bearer(String role){return "Bearer "+TestJwtHelper.jwt(role);}
}
