package com.edgecloud.device.controller;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;import com.edgecloud.device.security.*;import com.edgecloud.device.service.DeviceOrganisationService;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.context.annotation.Import;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.MockMvc;
@WebMvcTest(DeviceOrganisationController.class) @Import({DeviceSecurityConfig.class,EdgeCloudJwtAuthenticationFilter.class,JwtService.class}) class DeviceOrganisationControllerTest {
 @Autowired MockMvc mvc;@MockBean DeviceOrganisationService service;String p="11111111-1111-1111-1111-111111111111",g="22222222-2222-2222-2222-222222222222",d="33333333-3333-3333-3333-333333333333";
 @Test void unauthenticatedIsRejected()throws Exception{mvc.perform(get("/management/projects/"+p+"/groups")).andExpect(status().isUnauthorized());}
 @Test void viewerCannotReadOrMutate()throws Exception{String t=bearer("VIEWER");mvc.perform(get("/management/projects/"+p+"/groups").header("Authorization",t)).andExpect(status().isForbidden());mvc.perform(post("/management/projects/"+p+"/groups").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Production\"}")).andExpect(status().isForbidden());}
 @Test void adminOperatorAndProjectAdminFollowProjectScopedConvention()throws Exception{for(String role:java.util.List.of("ADMIN","OPERATOR","PROJECT_ADMIN"))mvc.perform(get("/management/projects/"+p+"/groups").header("Authorization",bearer(role))).andExpect(status().isOk());}
 @Test void validatesNamesAndAssignmentLists()throws Exception{String t=bearer("ADMIN");mvc.perform(post("/management/projects/"+p+"/groups").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\" \"}")).andExpect(status().isBadRequest());mvc.perform(post("/management/projects/"+p+"/groups/"+g+"/devices").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content("{\"deviceIds\":[]}")).andExpect(status().isBadRequest());}
 @Test void projectAdminCanAssignAndRemove()throws Exception{String t=bearer("PROJECT_ADMIN");mvc.perform(post("/management/projects/"+p+"/groups/"+g+"/devices").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content("{\"deviceIds\":[\""+d+"\"]}")).andExpect(status().isOk());mvc.perform(delete("/management/projects/"+p+"/groups/"+g+"/devices/"+d).header("Authorization",t)).andExpect(status().isNoContent());}
 private String bearer(String role){return "Bearer "+TestJwtHelper.jwt(role);}
}
