package com.edgecloud.device.service;

import com.edgecloud.device.dto.*; import com.edgecloud.device.entity.*; import com.edgecloud.device.exception.*; import com.edgecloud.device.repository.*;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.LocalDateTime; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class DeviceConfigurationServiceImpl implements DeviceConfigurationService {
 private static final int DEFAULT_POLLING=60,DEFAULT_HEARTBEAT=30,DEFAULT_METRICS=60;
 private final EdgeDeviceRepository devices; private final DeviceConfigurationRepository configs; private final DeviceConfigurationVersionRepository versions; private final DeviceConfigurationTemplateRepository templates; private final ObjectMapper json;
 public DeviceConfigurationServiceImpl(EdgeDeviceRepository devices,DeviceConfigurationRepository configs,DeviceConfigurationVersionRepository versions,DeviceConfigurationTemplateRepository templates,ObjectMapper json){this.devices=devices;this.configs=configs;this.versions=versions;this.templates=templates;this.json=json;}
 @Override @Transactional(readOnly=true) public DeviceConfigurationResponse get(UUID id){requireDevice(id,false);return configs.findById(id).map(this::response).orElse(defaultResponse(id));}
 @Override @Transactional public DeviceConfigurationResponse update(UUID id,DeviceConfigurationRequest r,UUID actor){requireDevice(id,true);DeviceConfiguration c=configs.findForUpdate(id).orElseGet(()->newConfiguration(id,actor));String changed=changed(c,r);if(changed.isEmpty())return response(c);apply(c,r);persistVersion(c,"UPDATED",changed,actor);return response(c);}
 @Override @Transactional(readOnly=true) public List<DeviceConfigurationVersionResponse> history(UUID id){requireDevice(id,false);return versions.findByDeviceIdOrderByVersionDesc(id).stream().map(this::versionResponse).toList();}
 @Override @Transactional public DeviceConfigurationResponse restore(UUID id,long version,UUID actor){requireDevice(id,true);DeviceConfigurationVersion source=versions.findByDeviceIdAndVersion(id,version).orElseThrow(()->new DeviceNotFoundException("Configuration version not found: "+version));DeviceConfiguration c=configs.findForUpdate(id).orElseGet(()->newConfiguration(id,actor));copy(c,source);persistVersion(c,"RESTORED","restoredFromVersion="+version,actor);return response(c);}
 @Override @Transactional(readOnly=true) public List<DeviceConfigurationTemplateResponse> templates(){return templates.findAllByOrderByNameAsc().stream().map(this::templateResponse).toList();}
 @Override @Transactional public DeviceConfigurationTemplateResponse createTemplate(DeviceConfigurationTemplateRequest r,UUID actor){if(templates.existsByNameIgnoreCase(r.name().trim()))throw new DuplicateConfigurationTemplateException("Configuration template already exists: "+r.name());DeviceConfigurationTemplate t=new DeviceConfigurationTemplate(UUID.randomUUID());LocalDateTime now=LocalDateTime.now();t.setCreatedAt(now);t.setCreatedBy(actor);apply(t,r);t.setUpdatedAt(now);t.setUpdatedBy(actor);return templateResponse(templates.save(t));}
 @Override @Transactional public DeviceConfigurationTemplateResponse updateTemplate(UUID id,DeviceConfigurationTemplateRequest r,UUID actor){DeviceConfigurationTemplate t=templates.findById(id).orElseThrow(()->new DeviceNotFoundException("Configuration template not found: "+id));if(templates.existsByNameIgnoreCaseAndIdNot(r.name().trim(),id))throw new DuplicateConfigurationTemplateException("Configuration template already exists: "+r.name());apply(t,r);t.setUpdatedAt(LocalDateTime.now());t.setUpdatedBy(actor);return templateResponse(templates.save(t));}
 @Override @Transactional public DeviceConfigurationResponse applyTemplate(UUID deviceId,UUID templateId,UUID actor){requireDevice(deviceId,true);DeviceConfigurationTemplate t=templates.findById(templateId).orElseThrow(()->new DeviceNotFoundException("Configuration template not found: "+templateId));DeviceConfiguration c=configs.findForUpdate(deviceId).orElseGet(()->newConfiguration(deviceId,actor));copy(c,t);persistVersion(c,"TEMPLATE_APPLIED","templateId="+templateId,actor);return response(c);}
 private EdgeDevice requireDevice(UUID id,boolean active){EdgeDevice d=(active?devices.findByIdForUpdate(id):devices.findById(id)).orElseThrow(()->new DeviceNotFoundException("Device not found: "+id));if(active&&!d.isActive())throw new InvalidDeviceLifecycleException("Inactive device configuration is read-only");return d;}
 private DeviceConfiguration newConfiguration(UUID id,UUID actor){DeviceConfiguration c=new DeviceConfiguration(id);c.setPollingIntervalSeconds(DEFAULT_POLLING);c.setHeartbeatIntervalSeconds(DEFAULT_HEARTBEAT);c.setMetricsCollectionIntervalSeconds(DEFAULT_METRICS);c.setEnvironment(DeviceEnvironment.DEVELOPMENT);c.setLoggingLevel(DeviceLoggingLevel.INFO);c.setApiEndpoint("");c.setTagsJson("[]");c.setVersion(0);c.setCreatedAt(LocalDateTime.now());c.setUpdatedAt(c.getCreatedAt());c.setUpdatedBy(actor);return c;}
 private void persistVersion(DeviceConfiguration c,String action,String fields,UUID actor){c.setVersion(c.getVersion()+1);c.setUpdatedAt(LocalDateTime.now());c.setUpdatedBy(actor);configs.save(c);versions.save(new DeviceConfigurationVersion(c,action,fields,actor));}
 private void apply(DeviceConfiguration c,DeviceConfigurationRequest r){c.setPollingIntervalSeconds(r.pollingIntervalSeconds());c.setHeartbeatIntervalSeconds(r.heartbeatIntervalSeconds());c.setMetricsCollectionIntervalSeconds(r.metricsCollectionIntervalSeconds());c.setEnvironment(r.environment());c.setApiEndpoint(clean(r.apiEndpoint()));c.setLoggingLevel(r.loggingLevel());c.setTagsJson(writeTags(r.tags()));}
 private void apply(DeviceConfigurationTemplate t,DeviceConfigurationTemplateRequest r){t.setName(r.name().trim());t.setDescription(clean(r.description()));t.setPollingIntervalSeconds(r.pollingIntervalSeconds());t.setHeartbeatIntervalSeconds(r.heartbeatIntervalSeconds());t.setMetricsCollectionIntervalSeconds(r.metricsCollectionIntervalSeconds());t.setEnvironment(r.environment());t.setApiEndpoint(clean(r.apiEndpoint()));t.setLoggingLevel(r.loggingLevel());t.setTagsJson(writeTags(r.tags()));}
 private void copy(DeviceConfiguration c,DeviceConfigurationVersion v){c.setPollingIntervalSeconds(v.getPollingIntervalSeconds());c.setHeartbeatIntervalSeconds(v.getHeartbeatIntervalSeconds());c.setMetricsCollectionIntervalSeconds(v.getMetricsCollectionIntervalSeconds());c.setEnvironment(v.getEnvironment());c.setApiEndpoint(v.getApiEndpoint());c.setLoggingLevel(v.getLoggingLevel());c.setTagsJson(v.getTagsJson());}
 private void copy(DeviceConfiguration c,DeviceConfigurationTemplate t){c.setPollingIntervalSeconds(t.getPollingIntervalSeconds());c.setHeartbeatIntervalSeconds(t.getHeartbeatIntervalSeconds());c.setMetricsCollectionIntervalSeconds(t.getMetricsCollectionIntervalSeconds());c.setEnvironment(t.getEnvironment());c.setApiEndpoint(t.getApiEndpoint());c.setLoggingLevel(t.getLoggingLevel());c.setTagsJson(t.getTagsJson());}
 private String changed(DeviceConfiguration c,DeviceConfigurationRequest r){List<String>x=new ArrayList<>();if(c.getPollingIntervalSeconds()!=r.pollingIntervalSeconds())x.add("pollingIntervalSeconds");if(c.getHeartbeatIntervalSeconds()!=r.heartbeatIntervalSeconds())x.add("heartbeatIntervalSeconds");if(c.getMetricsCollectionIntervalSeconds()!=r.metricsCollectionIntervalSeconds())x.add("metricsCollectionIntervalSeconds");if(c.getEnvironment()!=r.environment())x.add("environment");if(!Objects.equals(c.getApiEndpoint(),clean(r.apiEndpoint())))x.add("apiEndpoint");if(c.getLoggingLevel()!=r.loggingLevel())x.add("loggingLevel");if(!Objects.equals(c.getTagsJson(),writeTags(r.tags())))x.add("tags");return String.join(",",x);}
 private String writeTags(List<String> tags){try{return json.writeValueAsString(tags==null?List.of():tags.stream().map(String::trim).distinct().toList());}catch(Exception e){throw new IllegalArgumentException("Invalid tags");}}
 private List<String> readTags(String value){try{return json.readValue(value,new TypeReference<List<String>>(){});}catch(Exception e){throw new IllegalStateException("Stored tags are invalid",e);}}
 private String clean(String v){return v==null?"":v.trim();}
 private DeviceConfigurationResponse defaultResponse(UUID id){return new DeviceConfigurationResponse(id,DEFAULT_POLLING,DEFAULT_HEARTBEAT,DEFAULT_METRICS,DeviceEnvironment.DEVELOPMENT,"",DeviceLoggingLevel.INFO,List.of(),0,null,null,null,"STORED_ONLY");}
 private DeviceConfigurationResponse response(DeviceConfiguration c){return new DeviceConfigurationResponse(c.getDeviceId(),c.getPollingIntervalSeconds(),c.getHeartbeatIntervalSeconds(),c.getMetricsCollectionIntervalSeconds(),c.getEnvironment(),c.getApiEndpoint(),c.getLoggingLevel(),readTags(c.getTagsJson()),c.getVersion(),c.getCreatedAt(),c.getUpdatedAt(),c.getUpdatedBy(),"STORED_ONLY");}
 private DeviceConfigurationVersionResponse versionResponse(DeviceConfigurationVersion v){return new DeviceConfigurationVersionResponse(v.getVersion(),v.getPollingIntervalSeconds(),v.getHeartbeatIntervalSeconds(),v.getMetricsCollectionIntervalSeconds(),v.getEnvironment(),v.getApiEndpoint(),v.getLoggingLevel(),readTags(v.getTagsJson()),v.getAction(),List.of(v.getChangedFields().split(",")),v.getChangedBy(),v.getChangedAt());}
 private DeviceConfigurationTemplateResponse templateResponse(DeviceConfigurationTemplate t){return new DeviceConfigurationTemplateResponse(t.getId(),t.getName(),t.getDescription(),t.getPollingIntervalSeconds(),t.getHeartbeatIntervalSeconds(),t.getMetricsCollectionIntervalSeconds(),t.getEnvironment(),t.getApiEndpoint(),t.getLoggingLevel(),readTags(t.getTagsJson()),t.getCreatedAt(),t.getUpdatedAt(),t.getCreatedBy(),t.getUpdatedBy());}
}
