package com.edgecloud.device.service;
import com.edgecloud.device.dto.*; import com.edgecloud.device.entity.*; import com.edgecloud.device.exception.*; import com.edgecloud.device.repository.*;
import java.time.LocalDateTime; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class DeviceOrganisationServiceImpl implements DeviceOrganisationService {
 private final DeviceGroupRepository groups;private final DeviceTagRepository tags;private final DeviceGroupMembershipRepository memberships;private final DeviceTagAssignmentRepository assignments;private final EdgeDeviceRepository devices;private final ProjectScopeClient projects;
 public DeviceOrganisationServiceImpl(DeviceGroupRepository groups,DeviceTagRepository tags,DeviceGroupMembershipRepository memberships,DeviceTagAssignmentRepository assignments,EdgeDeviceRepository devices,ProjectScopeClient projects){this.groups=groups;this.tags=tags;this.memberships=memberships;this.assignments=assignments;this.devices=devices;this.projects=projects;}
 @Override @Transactional(readOnly=true) public List<DeviceGroupResponse> groups(UUID p,String q,String token){projects.requireProjectAccess(p,token);return groups.findByProjectIdAndNameContainingIgnoreCaseOrderByNameAsc(p,clean(q)).stream().map(this::groupResponse).toList();}
 @Override @Transactional(readOnly=true) public DeviceGroupResponse group(UUID p,UUID id,String token){projects.requireProjectAccess(p,token);return groupResponse(findGroup(p,id));}
 @Override @Transactional public DeviceGroupResponse createGroup(UUID p,DeviceGroupRequest r,UUID actor,String token){projects.requireProjectAccess(p,token);String normal=normalise(r.name());if(groups.existsByProjectIdAndNormalisedName(p,normal))throw conflict("Device group already exists in this project");DeviceGroup g=new DeviceGroup(UUID.randomUUID(),p);LocalDateTime now=LocalDateTime.now();apply(g,r,normal);g.setCreatedAt(now);g.setUpdatedAt(now);g.setCreatedBy(actor);g.setUpdatedBy(actor);return groupResponse(groups.save(g));}
 @Override @Transactional public DeviceGroupResponse updateGroup(UUID p,UUID id,DeviceGroupRequest r,UUID actor,String token){projects.requireProjectAccess(p,token);DeviceGroup g=findGroup(p,id);String normal=normalise(r.name());if(groups.existsByProjectIdAndNormalisedNameAndIdNot(p,normal,id))throw conflict("Device group already exists in this project");apply(g,r,normal);g.setUpdatedAt(LocalDateTime.now());g.setUpdatedBy(actor);return groupResponse(groups.save(g));}
 @Override @Transactional public void deleteGroup(UUID p,UUID id,String token){projects.requireProjectAccess(p,token);DeviceGroup g=findGroup(p,id);if(memberships.countByGroupId(id)>0)throw conflict("Remove all devices before deleting this group");groups.delete(g);}
 @Override @Transactional(readOnly=true) public List<DeviceGroupMembershipResponse> members(UUID p,UUID id,String token){projects.requireProjectAccess(p,token);findGroup(p,id);return memberships.findByGroupIdOrderByAssignedAtAsc(id).stream().map(this::membershipResponse).toList();}
 @Override @Transactional public List<DeviceGroupMembershipResponse> assignDevices(UUID p,UUID id,List<UUID> ids,UUID actor,String token){projects.requireProjectAccess(p,token);findGroup(p,id);for(UUID deviceId:new LinkedHashSet<>(ids)){projects.requireDeviceAssociation(p,deviceId,token);if(!devices.existsById(deviceId))throw new DeviceNotFoundException("Device not found: "+deviceId);DeviceGroupMembership.Id key=new DeviceGroupMembership.Id(id,deviceId);if(!memberships.existsById(key))memberships.save(new DeviceGroupMembership(id,deviceId,actor));}return memberships.findByGroupIdOrderByAssignedAtAsc(id).stream().map(this::membershipResponse).toList();}
 @Override @Transactional public void removeDevice(UUID p,UUID gid,UUID did,String token){projects.requireProjectAccess(p,token);findGroup(p,gid);projects.requireDeviceAssociation(p,did,token);memberships.deleteByGroupIdAndDeviceId(gid,did);}
 @Override @Transactional(readOnly=true) public List<DeviceTagResponse> tags(UUID p,String q,String token){projects.requireProjectAccess(p,token);return tags.findByProjectIdAndNameContainingIgnoreCaseOrderByNameAsc(p,clean(q)).stream().map(this::tagResponse).toList();}
 @Override @Transactional public DeviceTagResponse createTag(UUID p,DeviceTagRequest r,UUID actor,String token){projects.requireProjectAccess(p,token);String normal=normalise(r.name());if(tags.existsByProjectIdAndNormalisedName(p,normal))throw conflict("Device tag already exists in this project");DeviceTag t=new DeviceTag(UUID.randomUUID(),p);LocalDateTime now=LocalDateTime.now();apply(t,r,normal);t.setCreatedAt(now);t.setUpdatedAt(now);t.setCreatedBy(actor);t.setUpdatedBy(actor);return tagResponse(tags.save(t));}
 @Override @Transactional public DeviceTagResponse updateTag(UUID p,UUID id,DeviceTagRequest r,UUID actor,String token){projects.requireProjectAccess(p,token);DeviceTag t=findTag(p,id);String normal=normalise(r.name());if(tags.existsByProjectIdAndNormalisedNameAndIdNot(p,normal,id))throw conflict("Device tag already exists in this project");apply(t,r,normal);t.setUpdatedAt(LocalDateTime.now());t.setUpdatedBy(actor);return tagResponse(tags.save(t));}
 @Override @Transactional public void deleteTag(UUID p,UUID id,String token){projects.requireProjectAccess(p,token);DeviceTag t=findTag(p,id);assignments.deleteByTagId(id);tags.delete(t);}
 @Override @Transactional(readOnly=true) public List<DeviceTagResponse> deviceTags(UUID p,UUID did,String token){projects.requireDeviceAssociation(p,did,token);return tagsFor(assignments.findByDeviceIdOrderByAssignedAtAsc(did),p);}
 @Override @Transactional public List<DeviceTagResponse> assignTags(UUID p,UUID did,List<UUID> ids,UUID actor,String token){projects.requireDeviceAssociation(p,did,token);if(!devices.existsById(did))throw new DeviceNotFoundException("Device not found: "+did);Set<UUID>wanted=new LinkedHashSet<>(ids);List<DeviceTag> selected=tags.findAllByIdInAndProject(wanted,p);if(selected.size()!=wanted.size())throw new ProjectScopeAccessException("Project-scoped resource is not accessible");Map<UUID,DeviceTagAssignment> current=new HashMap<>();for(DeviceTagAssignment a:assignments.findByDeviceIdOrderByAssignedAtAsc(did))current.put(a.getTagId(),a);for(DeviceTagAssignment a:current.values())if(!wanted.contains(a.getTagId()))assignments.delete(a);for(UUID tid:wanted)if(!current.containsKey(tid))assignments.save(new DeviceTagAssignment(tid,did,actor));return selected.stream().sorted(Comparator.comparing(DeviceTag::getName,String.CASE_INSENSITIVE_ORDER)).map(this::tagResponse).toList();}
 @Override @Transactional public void removeTag(UUID p,UUID did,UUID tid,String token){projects.requireDeviceAssociation(p,did,token);findTag(p,tid);assignments.deleteByTagIdAndDeviceId(tid,did);}
 private DeviceGroup findGroup(UUID p,UUID id){return groups.findByIdAndProjectId(id,p).orElseThrow(()->new ProjectScopeAccessException("Project-scoped resource is not accessible"));}private DeviceTag findTag(UUID p,UUID id){return tags.findByIdAndProjectId(id,p).orElseThrow(()->new ProjectScopeAccessException("Project-scoped resource is not accessible"));}
 private void apply(DeviceGroup g,DeviceGroupRequest r,String n){g.setName(display(r.name()));g.setNormalisedName(n);g.setDescription(clean(r.description()));}private void apply(DeviceTag t,DeviceTagRequest r,String n){t.setName(display(r.name()));t.setNormalisedName(n);t.setDescription(clean(r.description()));}
 private String clean(String s){return s==null?"":s.trim();}private String display(String s){return s.trim().replaceAll("\\s+"," ");}private String normalise(String s){return display(s).toLowerCase(Locale.ROOT);}private OrganisationConflictException conflict(String m){return new OrganisationConflictException(m);}
 private DeviceGroupResponse groupResponse(DeviceGroup g){return new DeviceGroupResponse(g.getId(),g.getProjectId(),g.getName(),g.getDescription(),memberships.countByGroupId(g.getId()),g.getCreatedAt(),g.getUpdatedAt(),g.getCreatedBy(),g.getUpdatedBy());}private DeviceTagResponse tagResponse(DeviceTag t){return new DeviceTagResponse(t.getId(),t.getProjectId(),t.getName(),t.getDescription(),t.getCreatedAt(),t.getUpdatedAt(),t.getCreatedBy(),t.getUpdatedBy());}private DeviceGroupMembershipResponse membershipResponse(DeviceGroupMembership m){return new DeviceGroupMembershipResponse(m.getGroupId(),m.getDeviceId(),m.getAssignedAt(),m.getAssignedBy());}
 private List<DeviceTagResponse> tagsFor(List<DeviceTagAssignment> values,UUID p){Set<UUID> ids=new HashSet<>();values.forEach(v->ids.add(v.getTagId()));return tags.findAllByIdInAndProject(ids,p).stream().sorted(Comparator.comparing(DeviceTag::getName,String.CASE_INSENSITIVE_ORDER)).map(this::tagResponse).toList();}
}
