package com.edgecloud.device.service;
import com.edgecloud.device.dto.*;import com.edgecloud.device.entity.*;import com.edgecloud.device.exception.*;import com.edgecloud.device.repository.*;import java.time.*;import java.util.UUID;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class DeviceHeartbeatServiceImpl implements DeviceHeartbeatService {
 private final EdgeDeviceRepository devices;private final DeviceConfigurationRepository configs;private final DeviceHeartbeatHistoryRepository history;private final HeartbeatPolicyService policy;
 public DeviceHeartbeatServiceImpl(EdgeDeviceRepository d,DeviceConfigurationRepository c,DeviceHeartbeatHistoryRepository h,HeartbeatPolicyService p){devices=d;configs=c;history=h;policy=p;}
 @Transactional(readOnly=true) public HeartbeatStateResponse state(UUID id,LocalDateTime now){return response(require(id),now);}
 @Transactional public HeartbeatStateResponse record(UUID id,LocalDateTime at){EdgeDevice d=devices.findByIdForUpdate(id).orElseThrow(()->new DeviceNotFoundException("Device not found: "+id));if(!d.isActive())throw new InvalidDeviceLifecycleException("Inactive device cannot send heartbeats: "+id);LocalDateTime time=at==null?LocalDateTime.now():at;if(time.isAfter(LocalDateTime.now().plusMinutes(5)))throw new IllegalArgumentException("Heartbeat timestamp cannot be in the future");HeartbeatStatus previous=calculate(d,time).status();boolean recovered=previous==HeartbeatStatus.OFFLINE||previous==HeartbeatStatus.DELAYED;if(recovered)d.setLastRecoveryAt(time);if(d.getOnlineSince()==null||previous==HeartbeatStatus.OFFLINE||previous==HeartbeatStatus.UNKNOWN)d.setOnlineSince(time);d.setLastHeartbeat(time);d.setConsecutiveMissedHeartbeats(0);d.setHeartbeatState(HeartbeatStatus.ONLINE);d.setStatus(DeviceStatus.ONLINE);devices.save(d);history.save(new DeviceHeartbeatHistory(id,recovered?HeartbeatEventType.RECOVERED:HeartbeatEventType.RECEIVED,time,previous,HeartbeatStatus.ONLINE,0));return response(d,time);}
 @Transactional public void evaluateAll(LocalDateTime now){for(EdgeDevice d:devices.findByActiveTrue()){HeartbeatPolicyResult r=calculate(d,now);HeartbeatStatus previous=d.getHeartbeatState();boolean changed=previous!=r.status()||d.getConsecutiveMissedHeartbeats()!=r.consecutiveMissedHeartbeats();if(!changed)continue;d.setConsecutiveMissedHeartbeats(r.consecutiveMissedHeartbeats());d.setHeartbeatState(r.status());if(r.status()==HeartbeatStatus.OFFLINE&&previous!=HeartbeatStatus.OFFLINE){d.setStatus(DeviceStatus.OFFLINE);history.save(new DeviceHeartbeatHistory(d.getId(),HeartbeatEventType.OFFLINE,now,previous,HeartbeatStatus.OFFLINE,r.consecutiveMissedHeartbeats()));}else if(r.status()==HeartbeatStatus.DELAYED&&previous!=HeartbeatStatus.DELAYED){history.save(new DeviceHeartbeatHistory(d.getId(),HeartbeatEventType.DELAYED,now,previous,HeartbeatStatus.DELAYED,r.consecutiveMissedHeartbeats()));}devices.save(d);}}
 @Transactional(readOnly=true) public HeartbeatHistoryResponse history(UUID id,int page,int size){require(id);if(page<0||size<1||size>100)throw new IllegalArgumentException("Page must be at least 0 and size between 1 and 100");var p=history.findByDeviceIdOrderByHeartbeatAtDescIdDesc(id,PageRequest.of(page,size));return new HeartbeatHistoryResponse(p.map(e->new HeartbeatHistoryItemResponse(e.getId(),e.getEventType(),e.getHeartbeatAt(),e.getPreviousStatus(),e.getResultingStatus(),e.getMissedHeartbeats(),e.getRecordedAt())).getContent(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional(readOnly=true) public HeartbeatStatisticsResponse statistics(UUID id){require(id);LocalDateTime now=LocalDateTime.now();return new HeartbeatStatisticsResponse(id,history.countByDeviceId(id),history.countByDeviceIdAndEventTypeInAndHeartbeatAtBetween(id,java.util.List.of(HeartbeatEventType.RECEIVED,HeartbeatEventType.RECOVERED),now.minusHours(24),now.plusMinutes(1)),history.countByDeviceIdAndEventType(id,HeartbeatEventType.RECOVERED),history.countByDeviceIdAndEventType(id,HeartbeatEventType.OFFLINE));}
 private EdgeDevice require(UUID id){return devices.findById(id).orElseThrow(()->new DeviceNotFoundException("Device not found: "+id));}
 private HeartbeatPolicyResult calculate(EdgeDevice d,LocalDateTime now){DeviceConfiguration c=configs.findById(d.getId()).orElse(null);int interval=c==null?DeviceConfigurationServiceImpl.DEFAULT_HEARTBEAT:c.getHeartbeatIntervalSeconds();int timeout=c==null?DeviceConfigurationServiceImpl.DEFAULT_HEARTBEAT_TIMEOUT:c.getHeartbeatTimeoutSeconds();return policy.calculate(d.getLastHeartbeat(),d.getOnlineSince(),interval,timeout,now);}
 private HeartbeatStateResponse response(EdgeDevice d,LocalDateTime now){HeartbeatPolicyResult r=calculate(d,now);DeviceConfiguration c=configs.findById(d.getId()).orElse(null);int interval=c==null?DeviceConfigurationServiceImpl.DEFAULT_HEARTBEAT:c.getHeartbeatIntervalSeconds();int timeout=c==null?DeviceConfigurationServiceImpl.DEFAULT_HEARTBEAT_TIMEOUT:c.getHeartbeatTimeoutSeconds();return new HeartbeatStateResponse(d.getId(),r.status(),d.getLastHeartbeat(),r.nextExpectedHeartbeat(),interval,timeout,r.consecutiveMissedHeartbeats(),d.getLastRecoveryAt(),r.connectionDuration()==null?null:r.connectionDuration().getSeconds());}
}
